version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_calculator3
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      # For normal dev usage, your app might use fastapi_db by default
      # but let's also define a dedicated test DB for the local environment
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fastapi_test_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres
    container_name: postgres_db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # If you'd like, set this to 'fastapi_db' for dev,
      # but we'll also manually create fastapi_test_db in conftest.py or via init script
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  app-network:
    driver: bridge
